# Use the Node.js 16 Alpine base image
FROM node:16-alpine
# Set the user to 'node' for security purposes
USER node
# Create a directory structure for the application
RUN mkdir -p /home/node/app
# Set the working directory within the container
WORKDIR /home/node/app
# Copy the package.json file to the current directory
COPY --chown=node:node ./package.json ./
# Install application dependencies
RUN npm install
# Copy the application source code to the current directory
COPY --chown=node:node ./ ./
# Define the default command to start the application
CMD ["npm", "start"]



